export const posts = [
	{
		fullName: 'Vincent van Gogh',
		username: 'vincey1853',
		location: 'Zundert, Netherlands',
		avatar: 'images/avatar-vangogh.png',
		post: 'images/post-vangogh.png',
		comment: 'just took a few mushrooms lol',
		likes: 21492,
		like: 'images/like.png',
		comments: 'images/comment.png',
		share: 'images/share.png',
	},
	{
		fullName: 'Gustave Courbet',
		username: 'gus1819',
		location: 'Ornans, France',
		avatar: 'images/avatar-courbet.png',
		post: 'images/post-courbet.png',
		comment: "i'm feelin a bit stressed tbh",
		likes: 12502,
		like: 'images/like.png',
		comments: 'images/comment.png',
		share: 'images/share.png',
	},
	{
		fullName: 'Joseph Ducreux',
		username: 'jd1735',
		location: 'Paris, France',
		avatar: 'images/avatar-ducreux.png',
		post: 'images/post-ducreux.png',
		comment:
			'gm friends! which coin are YOU stacking up today?? post below and WAGMI!',
		likes: 15137,
		like: 'images/like.png',
		comments: 'images/comment.png',
		share: 'images/share.png',
	},
]
